#pragma once

namespace Minecraft
{
    enum class Key
    {
        // Numbers
        // TODO: rename these to Number0, Number1, etc.
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,

        // Letters
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,

        // Punctuation
        Grave,
        Minus,
        Equals,
        LeftBracket,
        RightBracket,
        BackSlash,
        SemiColon,
        Apostrophe,
        Comma,
        FullStop,
        ForwardSlash,

        // Function keys
        Escape,
        Enter,
        Space,
        Tab,
        Backspace,
        UpArrow,
        DownArrow,
        LeftArrow,
        RightArrow,
        PageUp,
        PageDown,
        Home,
        End,
        Insert,
        Delete,
        CapsLock,
        PrintScreen,
        LeftShift,
        LeftControl,
        LeftAlt,
        RightShift,
        RightControl,
        RightAlt,

        // F keys
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,

        // Keypad
        KeyPad0,
        KeyPad1,
        KeyPad2,
        KeyPad3,
        KeyPad4,
        KeyPad5,
        KeyPad6,
        KeyPad7,
        KeyPad8,
        KeyPad9,
        KeyPadAdd,
        KeyPadSubtract,
        KeyPadMultiply,
        KeyPadDivide,
        KeyPadDecimal,
        KeyPadEquals,
        KeyPadEnter,

        // Count
        Count,
    };
}
